kind: pipeline
type: docker
name: default

steps:
  - name: php8.1
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.meow.tf/tyler/php-laravel
      registry: registry.meow.tf
      tags:
        - php8.1
    depends_on:
      - clone
  - name: php8.2
    image: plugins/docker
    settings:
      build_args:
        PHP_VERSION: 8.2
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.meow.tf/tyler/php-laravel
      registry: registry.meow.tf
      tags:
        - php8
        - php8.2
    depends_on:
      - clone
  - name: php8.3
    image: plugins/docker
    settings:
      build_args:
        PHP_VERSION: 8.3
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.meow.tf/tyler/php-laravel
      registry: registry.meow.tf
      tags:
        - php8
        - php8.3
    depends_on:
      - clone