name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - php8

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.1, 8.2, 8.3]
        include:
          - php_version: 8.4
            php_redis_version: 6.1.0
            tags: ["php8", "php8.4"]
          - php_version: 8.3
            php_redis_version: 6.1.0
            tags: ["php8.3"]
          - php_version: 8.2
            php_redis_version: 5.3.7
            tags: ["php8.2"]
          - php_version: 8.1
            php_redis_version: 5.3.7
            tags: ["php8.1"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_REDIS_VERSION=${{ matrix.php_redis_version }}
          push: true
          tags: ${{ join(',', fromJSON(format('[{0}]', join(',', matrix.tags))).* | map(format('ghcr.io/auroradevllc/php-laravel:{0}', .)) ) }}
